spring:
  application:
    name: hospital
  datasource:
    password: 12345
    username: root
    url: jdbc:mysql://localhost:3306/hospital
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    com.application: DEBUG